spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: library
      #uri: mongodb+srv://rafaelgomez:Nt3U,ElELrsC2..}?(1]@clusterfacephi.1fhkn.mongodb.net/apiKotlin?retryWrites=true&w=majority
      repositories:
        type: auto